"""Emit Mermaid flowchart source. Renders natively on GitHub, GitLab and in
most Markdown previewers, and can be pasted into draw.io via
Arrange > Insert > Advanced > Mermaid."""

import re

from . import ir, theme

_SAFE = re.compile(r"[^A-Za-z0-9_]")

# words mermaid parses as syntax; a node id colliding with one breaks the chart
RESERVED = {"end", "graph", "flowchart", "subgraph", "class", "classdef", "click",
            "style", "direction", "linkstyle", "state", "note"}


def _mid(node_id):
    """Mermaid identifiers tolerate letters, digits and underscore only."""
    s = _SAFE.sub("_", node_id)
    if s.lower() in RESERVED or not (s[0].isalpha() or s[0] == "_"):
        s = "n_" + s
    return s


def _text(lines):
    out = []
    for l in lines:
        out.append(l.replace("#", "#35;").replace('"', "#quot;"))
    return "<br/>".join(out)


def render(doc, annotated=True, mode="normal", with_source=True):
    direction = doc.get("direction", "TD")
    idx = ir.index(doc)
    lines = ["%%{init: {'flowchart': {'curve': 'basis'}, 'theme': 'base'}}%%",
             "%%%% Generated by uxflow from %s.flow.json (hash %s)" % (doc["id"], ir.content_hash(doc)),
             "%% Do not edit by hand -- edit the IR and regenerate.",
             "flowchart " + direction]

    lanes = doc.get("lanes") or []
    if lanes:
        for lane in lanes:
            members = [n for n in doc["nodes"] if n.get("lane") == lane["id"]]
            if not members:
                continue
            lines.append('    subgraph lane_%s["%s"]' % (_mid(lane["id"]), lane["label"]))
            lines.append("    direction " + direction)
            for n in members:
                lines.append("    " + _node_line(n, annotated))
            lines.append("    end")
        orphan = [n for n in doc["nodes"] if not n.get("lane")]
        for n in orphan:
            lines.append("    " + _node_line(n, annotated))
    else:
        for n in doc["nodes"]:
            lines.append("    " + _node_line(n, annotated))

    lines.append("")
    for e in doc["edges"]:
        lines.append("    " + _edge_line(e, annotated))

    lines.append("")
    lines.extend(_class_defs(mode))
    lines.extend(_class_assignments(doc, mode))

    if with_source:
        srcs = [n for n in doc["nodes"] if n.get("source")]
        if srcs:
            lines.append("")
            lines.append("%% source anchors")
            for n in srcs:
                lines.append("%%%%   %s -> %s" % (_mid(n["id"]), n["source"]))
    return "\n".join(lines) + "\n"


def _node_line(node, annotated):
    shape = theme.SHAPES.get(node["type"], theme.SHAPES["screen"])
    open_, close = shape["mermaid"]
    body = _text(ir.node_lines(node, annotated=annotated))
    return "%s%s%s%s" % (_mid(node["id"]), open_, body, close)


def _edge_line(e, annotated):
    kind = e.get("kind", "neutral")
    arrow = {"happy": "==>", "error": "-.->", "edge": "-.->", "back": "-.->"}.get(kind, "-->")
    label = e.get("label", "")
    if annotated and e.get("condition"):
        label = (label + " [" + e["condition"] + "]").strip()
    if label:
        label = _text([label])
        return "%s %s|%s| %s" % (_mid(e["from"]), arrow, label, _mid(e["to"]))
    return "%s %s %s" % (_mid(e["from"]), arrow, _mid(e["to"]))


def _class_defs(mode):
    palette = theme.DIFF_COLORS if mode == "diff" else dict(theme.KIND_COLORS, **theme.PROBLEM_COLORS)
    out = []
    for name, c in palette.items():
        out.append("    classDef %s fill:%s,stroke:%s,color:%s,stroke-width:2px;"
                   % (name, c["fill"], c["stroke"], c["text"]))
    return out


def _class_assignments(doc, mode):
    groups = {}
    for n in doc["nodes"]:
        if mode == "diff":
            cls = n.get("_diff", "unchanged")
        else:
            cls = n.get("_problem") or n.get("kind", "neutral")
        groups.setdefault(cls, []).append(_mid(n["id"]))
    return ["    class %s %s;" % (",".join(ids), cls) for cls, ids in sorted(groups.items())]
