"""Emit editable draw.io (.drawio / mxGraph) XML from the IR + computed layout.

One file per flow, with several pages: draw.io renders each <diagram> element as a
tab at the bottom of the canvas. That removes the annotated/clean file duplication
entirely -- the reader switches tabs instead of opening a second file.
"""

from xml.sax.saxutils import escape, quoteattr

from . import ir, theme

LEGEND_W = 230


def _attr(v):
    return quoteattr(str(v))


def _label(lines, first_bold=True):
    """draw.io renders HTML in cell values when html=1.

    We HTML-escape the text content here; quoteattr() later handles XML escaping.
    Escaping twice would surface literal &lt;br&gt; in the diagram.
    """
    if not lines:
        return ""
    head = escape(lines[0])
    if first_bold:
        head = "<b>%s</b>" % head
    return "<br>".join([head] + [escape(l) for l in lines[1:]])


def _style(node, mode):
    c = theme.colors_for(node, mode)
    shape = theme.SHAPES.get(node["type"], theme.SHAPES["screen"])
    s = shape["drawio"]
    s += "fillColor=%s;strokeColor=%s;fontColor=%s;" % (c["fill"], c["stroke"], c["text"])
    s += "align=center;verticalAlign=middle;fontSize=12;spacing=4;"
    if node.get("_problem"):
        s += "strokeWidth=3;dashed=0;"
    if node.get("_diff") == "removed":
        s += "opacity=60;"
    return s


# --------------------------------------------------------------------- document
def render_pages(pages):
    """pages: [{name, doc, layout, annotated, mode, legend}] -> one .drawio file."""
    first = pages[0]
    out = ['<?xml version="1.0" encoding="UTF-8"?>']
    out.append("<!-- Generated by flowlint. Source of truth: %s.flow.json (hash %s). "
               "Edit the IR, not this file. -->"
               % (first["doc"]["id"], ir.content_hash(first["doc"])))
    out.append('<mxfile host="flowlint" agent="flowlint-1.3" type="device">')
    for i, page in enumerate(pages):
        out.extend(_page(page, i))
    out.append("</mxfile>")
    return "\n".join(out) + "\n"


def render(doc, lay, annotated=True, mode="normal", legend=True, name=None):
    """Single-page convenience wrapper (kept for tests and one-off use)."""
    return render_pages([{
        "name": name or doc["title"], "doc": doc, "layout": lay,
        "annotated": annotated, "mode": mode, "legend": legend,
    }])


def _page(page, index):
    doc, lay = page["doc"], page["layout"]
    annotated, mode = page["annotated"], page.get("mode", "normal")
    legend = page.get("legend", True)

    parts = []
    parts.append('  <diagram id=%s name=%s>'
                 % (_attr("%s-p%d" % (doc["id"], index)), _attr(page["name"])))

    page_w = max(1169, lay["width"] + (LEGEND_W + 60 if legend else 0))
    page_h = max(826, lay["height"] + 60)
    parts.append(
        '    <mxGraphModel dx="1400" dy="900" grid="1" gridSize="10" guides="1" tooltips="1" '
        'connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="%d" pageHeight="%d" '
        'math="0" shadow="0">' % (page_w, page_h))
    parts.append("      <root>")
    parts.append('        <mxCell id="0" />')
    parts.append('        <mxCell id="1" parent="0" />')

    parts.append(_vertex(
        "flowlint-title", "<b>%s</b>" % escape(doc["title"]),
        "text;html=1;align=left;verticalAlign=middle;fontSize=18;fontColor=#18181B;",
        20, 8, max(400, lay["width"] - 40), 28))

    for box in lay["lanes"]:
        color = box.get("color") or theme.LANE_DEFAULT_COLORS[box["i"] % len(theme.LANE_DEFAULT_COLORS)]
        style = ("swimlane;html=1;startSize=34;horizontal=1;rounded=0;"
                 "fillColor=%s;strokeColor=#CBD5E1;fontColor=#334155;fontSize=13;"
                 "fontStyle=1;swimlaneFillColor=%s;" % (color, color))
        parts.append(_vertex("lane-" + box["id"], escape(box["label"]), style,
                             box["x"], box["y"], box["w"], box["h"]))

    for node in doc["nodes"]:
        g = lay["nodes"][node["id"]]
        value = _label(ir.node_lines(node, annotated=annotated))
        style = _style(node, mode)
        tooltip = node.get("source") or ""
        if node.get("route"):
            tooltip = node["route"] + ("  ·  " + tooltip if tooltip else "")
        cid = "n-" + node["id"]
        if tooltip:
            parts.append('        <UserObject label=%s tooltip=%s id=%s>'
                         % (_attr(value), _attr(tooltip), _attr(cid)))
            parts.append('          <mxCell style=%s vertex="1" parent="1">' % _attr(style))
            parts.append('            <mxGeometry x="%d" y="%d" width="%d" height="%d" as="geometry" />'
                         % (g["x"], g["y"], g["w"], g["h"]))
            parts.append("          </mxCell>")
            parts.append("        </UserObject>")
        else:
            parts.append(_vertex(cid, value, style, g["x"], g["y"], g["w"], g["h"]))

    parts.extend(_edges(doc, lay, annotated, mode))

    if legend:
        parts.extend(_legend(doc, lay, mode))

    parts.append("      </root>")
    parts.append("    </mxGraphModel>")
    parts.append("  </diagram>")
    return parts


def _edges(doc, lay, annotated, mode):
    """Edges with explicit routing.

    draw.io's auto-router does not know about the layout we computed, so left to
    itself it runs several edges down the same pixel column and stacks their
    labels on top of each other. We already know where every node sits, so we
    tell it: which side to leave from, which corridor to travel along, and where
    to put the label.
    """
    geom = lay["nodes"]
    out = []
    corridors = {}
    used_labels = []

    for i, e in enumerate(doc["edges"]):
        kind = e.get("kind", "neutral")
        a, b = geom[e["from"]], geom[e["to"]]
        downward = b["y"] >= a["y"] + a["h"]
        same_column = abs((a["x"] + a["w"] / 2) - (b["x"] + b["w"] / 2)) < 8

        style = "edgeStyle=orthogonalEdgeStyle;rounded=1;html=1;jettySize=auto;orthogonalLoop=1;"
        style += theme.EDGE_STYLES.get(kind, theme.EDGE_STYLES["neutral"])
        style += "fontSize=11;fontColor=#3F3F46;labelBackgroundColor=#FFFFFF;"
        # Fixing the exit and entry sides stops draw.io from picking a different
        # anchor on every reopen, which is what makes edges cross for no reason.
        if downward:
            style += "exitX=0.5;exitY=1;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;"
        elif b["y"] + b["h"] <= a["y"]:                       # going back up
            style += "exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=1;entryY=0.5;entryDx=0;entryDy=0;"
        if mode == "diff" and e.get("_diff") == "removed":
            style += "opacity=50;"
        if mode == "diff" and e.get("_diff") == "added":
            style += "strokeWidth=3;"

        label = e.get("label", "")
        if annotated and e.get("condition"):
            label = (label + "\n[" + e["condition"] + "]").strip()
        value = escape(label).replace("\n", "<br>") if label else ""

        points = []
        label_pt = None
        if downward and not same_column:
            # One horizontal run per (source rank, target rank) pair, each in its
            # own lane so parallel edges never share a line.
            key = (round(a["y"] + a["h"]), round(b["y"]))
            slot = corridors.setdefault(key, 0)
            corridors[key] = slot + 1
            gap = b["y"] - (a["y"] + a["h"])
            mid = a["y"] + a["h"] + max(14, min(gap - 14, gap / 2 + (slot - 1) * 12))
            points = [(a["x"] + a["w"] / 2, mid), (b["x"] + b["w"] / 2, mid)]
            label_pt = ((a["x"] + a["w"] / 2 + b["x"] + b["w"] / 2) / 2, mid)
        elif b["y"] + b["h"] <= a["y"]:
            key = ("back", round(min(a["y"], b["y"])))
            slot = corridors.setdefault(key, 0)
            corridors[key] = slot + 1
            side = max(a["x"] + a["w"], b["x"] + b["w"]) + 30 + slot * 18
            points = [(side, a["y"] + a["h"] / 2), (side, b["y"] + b["h"] / 2)]
            label_pt = (side, (a["y"] + a["h"] / 2 + b["y"] + b["h"] / 2) / 2)

        if value and label_pt:
            label_pt = _free_label(label_pt, len(label) * 6.0, 16, used_labels)

        out.append('        <mxCell id=%s value=%s style=%s edge="1" parent="1" source=%s target=%s>'
                   % (_attr("e-%d" % i), _attr(value), _attr(style),
                      _attr("n-" + e["from"]), _attr("n-" + e["to"])))
        out.append('          <mxGeometry relative="1" as="geometry">')
        if points:
            out.append('            <Array as="points">')
            for px, py in points:
                out.append('              <mxPoint x="%d" y="%d" />' % (round(px), round(py)))
            out.append("            </Array>")
        if value and label_pt:
            out.append('            <mxPoint x="%d" y="%d" as="offset" />'
                       % (0, round(label_pt[1] - _midpoint_y(a, b))))
        out.append("          </mxGeometry>")
        out.append("        </mxCell>")
    return out


def _midpoint_y(a, b):
    return (a["y"] + a["h"] / 2 + b["y"] + b["h"] / 2) / 2


def _free_label(point, w, h, used):
    """Nudge a label vertically until it stops overlapping earlier ones."""
    x, y = point
    for step in range(9):
        for direction in ((1, -1) if step else (1,)):
            cy = y + direction * step * (h + 2)
            rect = (x - w / 2, cy - h / 2, x + w / 2, cy + h / 2)
            if not any(rect[0] < o[2] and o[0] < rect[2] and
                       rect[1] < o[3] and o[1] < rect[3] for o in used):
                used.append(rect)
                return (x, cy)
    return (x, y)


def _vertex(cid, value, style, x, y, w, h):
    return ('        <mxCell id=%s value=%s style=%s vertex="1" parent="1">\n'
            '          <mxGeometry x="%d" y="%d" width="%d" height="%d" as="geometry" />\n'
            '        </mxCell>' % (_attr(cid), _attr(value), _attr(style), x, y, w, h))


def _legend(doc, lay, mode):
    x = lay["width"] + 30
    y = 60
    out = [_vertex("legend-title", "<b>Legend</b>",
                   "text;html=1;align=left;fontSize=13;fontColor=#18181B;", x, y - 26, LEGEND_W, 20)]

    if mode == "diff":
        items = [(k, theme.DIFF_COLORS[k], k) for k in ("added", "removed", "changed", "unchanged")]
    else:
        items = [(k, theme.KIND_COLORS[k], {
            "happy": "happy path", "error": "error handling",
            "edge": "edge case", "neutral": "infrastructure"}[k])
            for k in ("happy", "error", "edge", "neutral")]
        used_problems = sorted({n["_problem"] for n in doc["nodes"] if n.get("_problem")})
        items += [(p, theme.PROBLEM_COLORS[p], p) for p in used_problems]

    for i, (key, c, label) in enumerate(items):
        out.append(_vertex(
            "legend-%s" % key, escape(label),
            "rounded=1;arcSize=8;html=1;fillColor=%s;strokeColor=%s;fontColor=%s;fontSize=11;align=left;spacingLeft=8;"
            % (c["fill"], c["stroke"], c["text"]),
            x, y + i * 32, LEGEND_W, 26))

    y2 = y + len(items) * 32 + 14
    shapes = [("screen", "screen / route"), ("decision", "decision"), ("api", "API call"),
              ("data", "data store"), ("modal", "modal / sheet"), ("external", "leaves the app")]
    out.append(_vertex("legend-shapes", "<b>Shapes</b>",
                       "text;html=1;align=left;fontSize=13;fontColor=#18181B;", x, y2 - 22, LEGEND_W, 20))
    for i, (t, label) in enumerate(shapes):
        st = theme.SHAPES[t]["drawio"] + "fillColor=#FFFFFF;strokeColor=#71717A;fontColor=#27272A;fontSize=11;"
        out.append(_vertex("legend-shape-%s" % t, escape(label), st, x, y2 + i * 40, LEGEND_W, 32))
    return out
